name: Android CI

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 手动触发也可以

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'  # 使用你项目所需的 Gradle 版本

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: List build directory
        run: ls -l app/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
